/* cmdline.h */

/* File autogenerated by gengetopt version 2.6  */

#ifndef cmdline_h
#define cmdline_h

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

/* Don't define PACKAGE and VERSION if we use automake.  */
#if defined PACKAGE
#  undef PACKAGE
#endif
#define PACKAGE "mptris"
#if defined VERSION
#  undef VERSION
#endif
#define VERSION "1.9"

struct gengetopt_args_info {
  int level_arg;	/* The difficulty level.  */
  int autodisplay_flag;	/* Displays the game board automatically (default=on).  */

  int help_given ;	/* Whether help was given.  */
  int version_given ;	/* Whether version was given.  */
  int level_given ;	/* Whether level was given.  */
  int autodisplay_given ;	/* Whether autodisplay was given.  */
} ;

int cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info);

void cmdline_parser_print_help(void);
void cmdline_parser_print_version(void);

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* cmdline_h */
